# -*- coding: utf-8 -*-
# Deployment settings for brixpath.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Developer/Marmalade/6.1/s3e/makefile_builder/mkb.py', '--buildenv=xcode', '/Users/codemanki/projects/blackberry/brixpath/brixpath.mkb', '--deploy-only']
mkb = '/Users/codemanki/projects/blackberry/brixpath/brixpath.mkb'
mkf = ['/Developer/Marmalade/6.1/modules/iwgx/iwgx.mkf', '/Developer/Marmalade/6.1/modules/iwgeom/iwgeom.mkf', '/Developer/Marmalade/6.1/modules/iwutil/iwutil.mkf', u'/Users/codemanki/.local/share/marmalade/packages/6.1.1/libjpeg_6b/libjpeg.mkf', u'/Users/codemanki/.local/share/marmalade/packages/6.1.1/libpng_1.2.34/libpng.mkf', u'/Users/codemanki/.local/share/marmalade/packages/6.1.1/zlib_1.2.4/zlib.mkf', '/Developer/Marmalade/6.1/modules/iwresmanager/iwresmanager.mkf', '/Developer/Marmalade/6.1/modules/iwgl/iwgl.mkf', '/Developer/Marmalade/6.1/modules/iw2d/iw2d.mkf', '/Developer/Marmalade/6.1/modules/iwgxfont/iwgxfont.mkf', u'/Users/codemanki/.local/share/marmalade/packages/6.1.1/tiniconv_1.0.1/tiniconv.mkf']

class DeployConfig(object):
    os = ['playbook']
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/codemanki/projects/blackberry/brixpath/data/test.json', 'test.json', 0),
    ('/Users/codemanki/projects/blackberry/brixpath/data-ram/data-gles1/brixpath.group.bin,/Users/codemanki/projects/blackberry/brixpath/data/brixpath.group.bin', 'brixpath.group.bin', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    os = ['playbook']
    embed_icf = -1
    name = 'brixpath'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'brixpath'
    long_caption = 'brixpath'
    version = [0, 0, 1]
    config = ['/Users/codemanki/projects/blackberry/brixpath/data/app.icf']
    data_dir = '/Users/codemanki/projects/blackberry/brixpath/data'
    iphone_link_lib = []
    playbook_author = 'OGames'
    linux_ext_lib = []
    iphone_link_libdir = []
    playbook_authorid = 'gYAAgFre9ZSmzOiPUomMtAKofug'
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'x86' : {
                   'debug'   : r'/Users/codemanki/projects/blackberry/brixpath/build_brixpath_xcode/build/Debug/brixpath.s86',
                   'release' : r'/Users/codemanki/projects/blackberry/brixpath/build_brixpath_xcode/build/Release/brixpath.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/codemanki/projects/blackberry/brixpath/build_brixpath_xcode/build/Debug ARM/brixpath.s3e',
                   'release' : r'/Users/codemanki/projects/blackberry/brixpath/build_brixpath_xcode/build/Release ARM/brixpath.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
